apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: bar
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: wertsaq/nginx:v0.1.2
          ports:
            - containerPort: 80
